apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hamousabs-dev
data:
  app.js: |
    const express = require('express');
    const app = express();
    const port = 3000;

    app.get('/', (req, res) => {
      res.send('<h1 style="color: #2c3e50; font-family: sans-serif; text-align: center; margin-top: 50px;">🚀 Félicitations !</h1><p style="text-align: center; font-family: sans-serif;">Ton serveur Web fonctionne parfaitement sur OpenShift via GitHub Actions.</p>');
    });

    app.listen(port, () => {
      console.log('App running on port ' + port);
    });

  nginx.conf: |
    server {
        listen 8080;
        
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }